### ISSUE TITLE
One-way interaction for ios-minicap

### ISSUE THREAD

**Issue by TuHuynhVan** [nwlunatic/ios-minicap#15]
**Steps to reproduce**
1. Navigate to ios-minicap folder, ./run.sh
2. Open another terminal windows:
cd example
npm install
node app.js

**Expected results**
1. What user performs on iPhone should reflect in real-time on localhost:9002
2. User can use web interface by accessing to localhost:9002 to interact to the phone

**Actual results**
1. OK
2. User couldn't do that

**Environment(version of libraries, mac OS, iOS, etc)**
iOS: 10.2
MacOS: 10.11.6
XCode: 7.3.1

**Comment by TuHuynhVan** [comment]
Just recognized that was a dummy question as if we could interact 2-way, we would have it in our current STF...

Sorry for that question!

**Comment by nwlunatic** [comment]
No problem, thanks for you interest. Either way, `ios-minicap` won't have this functionality, it sound like another standalone component (app), like `ios-minitouch`.
