### ISSUE TITLE
Browsers on other computer can not get Iphone screen

### ISSUE THREAD

**Issue by yuzhidi** [nwlunatic/ios-minicap#16]
**Steps to reproduce**
./run.sh
node app.js

**Expected results**
Browser (Chrome ) on other computer can get iphone screen pictures

**Actual results**
Broswer on local mac can get iphone screen.
Browsers on other computer can not get iphone screen.
Browsers on other computer can get other http service on the mac which connected Iphone.

**Environment(version of libraries, mac OS, iOS, etc)**
OS X 10.11.6

**Comment by sorccu** [comment]
The example does not cover that use case. It's only an example and you have to modify it.
