### ISSUE TITLE
frame format

### ISSUE THREAD

**Issue by ketan077** [nwlunatic/ios-minicap#19]
I have one query about frame format.which format we are getting frame ?

**Comment by sorccu** [comment]
The README tells you.

**Comment by ketan077** [comment]
from device in which format we are getting?

**Comment by sorccu** [comment]
It is literally right there in the README.

**Comment by ketan077** [comment]
i saw your code. only one confusion i have that from device are u getting raw data and after are u converting to jpeg format? or from device are u getting jpeg format frame?

**Comment by sorccu** [comment]
The original format is x264.

**Comment by ketan077** [comment]
that's what i'm asking. i explore your code. every frame you are converting in to jpeg file. thanks

**Comment by ketan077** [comment]
is it possible to convert (The original format is x264) x264 format to raw data or png image frame?

**Comment by sorccu** [comment]
Sure. But that would be your task!

**Comment by ketan077** [comment]
give me some hint because i can't able to find for convertion x264 to raw or png data

**Comment by sorccu** [comment]
I'm not withholding information from you. If you need it, you build it. I
don't need it right now so I have no reason to look it up for you.

**Comment by ketan077** [comment]
at list you can give some direction otherwise if i need it, i must have to do !!!

**Comment by sorccu** [comment]
Right now you are basically demanding free work from us. That is not how
open source works.

**Comment by ketan077** [comment]
ohkk as u wish Thanks

**Comment by ketan077** [comment]
one question. there is class called Frame in your code. in that class frame->data exactly is it x264(stream data) type of data or different format type of data?

**Comment by ketan077** [comment]
done. right now i can able to convert X264 to png and also i can able to convert in to rgb

**Comment by sorccu** [comment]
Well done :)

**Comment by ketan077** [comment]
heyy one question. whenever i link any static library in cmake file ,i'm getting "undefined symbols for architecture x86_64" this error.if u know then help me.
