### ISSUE TITLE
Using ios-minicap for connecting iDevices like Android

### ISSUE THREAD

**Issue by TuHuynhVan** [nwlunatic/ios-minicap#2]
Hi @sorccu 
 Thank you for your great work to bring to us a free-tool like openSTF!

I see ios-minicap but I don;t know how to use it for connecting to iDevices like openSTF supports for Android devices?

Thank you!
Tu

**Comment by sorccu** [comment]
Ios-minicap was made by @nwlunatic originally.

It's new and you can't use it with STF yet. Have patience.

**Comment by TuHuynhVan** [comment]
Hi @sorccu,

Thank you so much! And thanks @nwlunatic as well!
You guys are super! 

Thank you all again!
