### ISSUE TITLE
Using  IOS-minicap Connection problem

### ISSUE THREAD

**Issue by lfjking** [nwlunatic/ios-minicap#21]
`
 $ brew install libjpeg-turbo
Updating Homebrew...
Warning: jpeg-turbo is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version

$ brew install --force  libjpeg-turbo
Updating Homebrew...
Warning: jpeg-turbo-1.5.1 already installed, it's just not linked.
`

I can't use it. help

**Comment by sorccu** [comment]
Can't help you with that, you have to get it installed yourself. Seems like you've got another non-brew version installed already.
