### ISSUE TITLE
 Error: connect ECONNREFUSED 127.0.0.1:12345

### ISSUE THREAD

**Issue by yxys01** [nwlunatic/ios-minicap#25]
Thanks for your answer .
But,when i run node app.js,i got this error:
Listening on port 9002
Got a client
{ Error: connect ECONNREFUSED 127.0.0.1:12345
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 12345 }
Be sure to run ios-minicap on port 12345

**Comment by sorccu** [comment]
The README covers that. You have to have run.sh running at the same time.

**Comment by yxys01** [comment]
In fact,i have run.sh running at the same time,and i still got this erroe.

**Comment by sorccu** [comment]
Then perhaps it didn't actually start successfully. Note that the screen of
your device must be on.

**Comment by yxys01** [comment]
$ ./run.sh
++ system_profiler SPUSBDataType
++ sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ *Serial Number: *(.+)/\1/p'
+ UDID=0c6c0a77471f5ae76dfdc55b57e0d1502ab92aab
+ PORT=12345
+ RESOLUTION=400x600
+ ./build/ios_minicap --udid 0c6c0a77471f5ae76dfdc55b57e0d1502ab92aab --port 12345 --resolution 400x600
EnableDALDevices
2017-07-31 12:24:26.081 ios_minicap[80709:3237274] Available devices:
2017-07-31 12:24:26.081 ios_minicap[80709:3237274] 0c6c0a77471f5ae76dfdc55b57e0d1502ab92aab
2017-07-31 12:24:26.081 ios_minicap[80709:3237274] CC24414NH0XF9T9C7

**Comment by sorccu** [comment]
It's not running. There isn't enough output.

**Comment by yxys01** [comment]
How to solve this problem？

**Comment by nwlunatic** [comment]
Your log haven't reach resolution line, so, probably ios-minicap could not get first frame.
Make sure your device screen is active. You may also try to reconnect device.

**Comment by yxys01** [comment]
Thanks for your answer and sharing.
I kill other port,and restart this successfully.
Thanks a lot.

**Comment by yxys01** [comment]
Is there a screenshot feature for ios-minicap？

**Comment by sorccu** [comment]
No. Use idevicescreenshot if you need that.
