### ISSUE TITLE
Devices's screen is not showing up

### ISSUE THREAD

**Issue by TuHuynhVan** [nwlunatic/ios-minicap#33]
I just got a simple frame without device's screen. Could you possibly help me to point out some clues?

<img width="320" alt="screen shot 2017-10-20 at 10 20 17" src="https://user-images.githubusercontent.com/18535553/31803949-b4d81ad4-b580-11e7-809f-d7c8429968f9.png">

**Comment by sorccu** [comment]
The example is just an example. It's not meant to be 100% reliable. That being said, it's impossible to say anything without seeing the full log output from both minicap and the node app (both of which you do have running at the same time, right)?

Also, the device screen must be on or you won't see anything.

**Comment by TuHuynhVan** [comment]
Thanks @sorccu for rocket response!
It seems there is just only one client can request the socket at same time.
Let me dig more.

Could you possibly help me to point out any good source to build webview and catch the websocket to get device screen?

**Comment by sorccu** [comment]
Like I said earlier it's a limitation of the Apple APIs. You can NOT have the screen of multiple devices open at once.

**Comment by TuHuynhVan** [comment]
Thank you anyway!
