### ISSUE TITLE
Can't get connection and no error when run node app.js

### ISSUE THREAD

**Issue by HeartIsBeat** [nwlunatic/ios-minicap#34]
**Steps to reproduce**
![image](https://user-images.githubusercontent.com/20472976/31811159-120d34ac-b5b1-11e7-8910-6ae48e104a33.png)
![image](https://user-images.githubusercontent.com/20472976/31811168-1b264290-b5b1-11e7-8324-7fa70b5f92db.png)

**Expected results**

**Actual results**

**Environment(version of libraries, mac OS, iOS, etc)**
![image](https://user-images.githubusercontent.com/20472976/31811427-1ac8603e-b5b2-11e7-8f48-15f66642eb52.png)
node is v8.1.4
using iphone6

**Comment by sorccu** [comment]
Need more details. It looks like it’s working fine.

The screen must be on though.

**Comment by HeartIsBeat** [comment]
@sorccu Screen is on though always.
![image](https://user-images.githubusercontent.com/20472976/31811338-ca81f6c6-b5b1-11e7-97e9-e73d787717c9.png)

**Comment by sorccu** [comment]
Try without charles?

**Comment by HeartIsBeat** [comment]
No charles!
I restart mac, and run node app.js, the web log is the same.

**Comment by sorccu** [comment]
If you don’t have charles running, why is it showing the charles error page?

**Comment by HeartIsBeat** [comment]
Open on Safari http://localhost:9002, can't connect server

**Comment by HeartIsBeat** [comment]
O, have error log on console!!!!
![image](https://user-images.githubusercontent.com/20472976/31812014-35506832-b5b4-11e7-9e07-9664a7bf7fe7.png)

**Comment by HeartIsBeat** [comment]
@sorccu Thank you very mush! It is ok using safari not chrome.
