### ISSUE TITLE
webdriveragent is running connect to ios-minicap will lead to error like "Connection to WDA timed out"

### ISSUE THREAD

**Issue by zhoudaqiang** [nwlunatic/ios-minicap#36]
hello,i want to use  ios-minicap combine with appium(when case error will user ios-minicap scrennshot),but when i connect to  ios-minicap server errors happend like this:
'''
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[XCUITest] Connection to WDA timed out
'''
and i want to know why this happend? and how to avoid it  thank you!

                                                                                                     best wish to you!!

**Comment by sorccu** [comment]
We do NOT support WDA. It’s a nightmare. Please ask the WDA guys.

**Comment by zhoudaqiang** [comment]
thank you very much!
