### ISSUE TITLE
build fail when I use ./build.sh

### ISSUE THREAD

**Issue by zhangying19871987** [nwlunatic/ios-minicap#38]
when I use the command ./build.sh
I get an error as follow:

/Users/zhangying/Downloads/ios-minicap-master/src/JpegEncoder.hpp:7:10: fatal error:
      'turbojpeg.h' file not found
#include <turbojpeg.h>
         ^~~~~~~~~~~~~
1 error generated.

**Comment by sorccu** [comment]
Fetch submodules.

**Comment by zhangying19871987** [comment]
can you tell me the specific methods

**Comment by sorccu** [comment]
Read the README.
