### ISSUE TITLE
can ios-minicap support multiple devices now?

### ISSUE THREAD

**Issue by qingranfjj** [nwlunatic/ios-minicap#39]
I thought update the run.sh ,make UDID、PROT as parameter,then can support multiple devices，I dont know if it can work，I have not debuged successfully yet.

**Comment by qingranfjj** [comment]
I thought update the run.sh ,make UDID、PROT as parameter,then can support multiple devices，I dont know if it can work，I have not debuged successfully yet.

**Comment by sorccu** [comment]
Doesn't work as far as I know. Apple needs to update the framework ios-minicap uses. I've created something else entirely but can't publish it.
