### ISSUE TITLE
[help] why the width & height is not the real size of iphone?

### ISSUE THREAD

**Issue by luoshangyu** [nwlunatic/ios-minicap#42]
Dear ios-minicap author,

Why the width & height is smaller used by CVPixelBufferRef by ios-minicap than the real screen size?

I'm try to implement a web app which can remote control ios, but the size is not the same.
ios-minicap use CVPixelBufferRef's width & height, e.g. iphone 6 plus is 1920*1080, but ios-minicap got 600 * 400 and, use 600/400 to set the canvas' size.

Why not make it the real screen size?

**Comment by nwlunatic** [comment]
It is hardcoded in [`run.sh`](https://github.com/openstf/ios-minicap/blob/master/run.sh#L7).
You can provide the resolution you want
