### ISSUE TITLE
minicap only support lignting cable?

### ISSUE THREAD

**Issue by scvjx** [nwlunatic/ios-minicap#47]
example, iphone4 or iphone4s   that is not lignting cable   

minicap is not support them?

**Comment by sorccu** [comment]
It does not like I just told you.

**Comment by scvjx** [comment]
thinks 
If I use a shift cable that plunges in iphone4s   .Lighting cable plunges in the kit.
is it work?

**Comment by sorccu** [comment]
No. You can try though, but expect nothing.

**Comment by scvjx** [comment]
OK,I'll try.
Would you simply tell me why minicap can not support 30pin cable?
Because I saw that a iphone4 remote control page in a Chinese company website.I guess they also use minicap. 
http://ctscatp.com.cn/1.png    it is my prtscn...

**Comment by sorccu** [comment]
It uses the same Apple framework as QuickTime, which doesn't support non-lightning devices.

Any company that makes money, Chinese or not, is able to invest some of that into research and development. They have likely spent a lot of time trying to find another performant way to support the older models, and it seems that they've succeeded. You should not expect the same from an open source project.

Perhaps you can ask that company if they'd be willing to share their method.

All I can say is that the framework provided by Apple does not support older devices.
