### ISSUE TITLE
A Mac connects two iOS devices at the same time， and use mirror function at the same time. Will it work?

### ISSUE THREAD

**Issue by JamesChungZLL** [nwlunatic/ios-minicap#49]
**Steps to reproduce**

**Expected results**

**Actual results**

**Environment(version of libraries, mac OS, iOS, etc)**

**Comment by sorccu** [comment]
Multiple devices are not supported due to limitations in the Apple APIs the project uses.

**Comment by JamesChungZLL** [comment]
Thanks for your reply, I want ask which api, and what this api work for? 
Is there anyway to support multiple devices with reducing fluency, however not reducing too much?
