### ISSUE TITLE
Cannot use iPhone8_ios11.3.1, This app is not authorized to use iPhone8_ios11.3.1

### ISSUE THREAD

**Issue by yuzhidi** [nwlunatic/ios-minicap#50]
**Steps to reproduce**
$ bash run.sh
++ system_profiler SPUSBDataType
++ sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ *Serial Number: *(.+)/\1/p'
+ UDID=c21889e091ee2ea39dea67fc5a47f4bc7777d5ca
+ PORT=12345
+ RESOLUTION=400x600
+ ./bin/ios_minicap --udid c21889e091ee2ea39dea67fc5a47f4bc7777d5ca --port 12345 --resolution 400x600
EnableDALDevices
2018-11-26 17:49:36.214 ios_minicap[1248:23629] Available devices:
2018-11-26 17:49:36.214 ios_minicap[1248:23629] c21889e091ee2ea39dea67fc5a47f4bc7777d5ca
2018-11-26 17:49:36.214 ios_minicap[1248:23629] CC253476BLYG1HNBB
2018-11-26 17:49:36.235 ios_minicap[1248:23629] Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use iPhone8_ios11.3.1" UserInfo={NSLocalizedFailureReason=This app is not authorized to use iPhone8_ios11.3.1., AVErrorDeviceKey=<AVCaptureDALDevice: 0x7fd590429c20 [iPhone8_ios11.3.1][c21889e091ee2ea39dea67fc5a47f4bc7777d5ca]>, NSLocalizedDescription=Cannot use iPhone8_ios11.3.1}

**Expected results**

can use ios-minicap

**Actual results**
Cannot use iPhone8_ios11.3.1
This app is not authorized to use iPhone8_ios11.3.1

**Environment(version of libraries, mac OS, iOS, etc)**
macOS Mojave 10.14

**Comment by sorccu** [comment]
Did you click on “trust this computer” on the phone?

**Comment by yuzhidi** [comment]
> Did you click on “trust this computer” on the phone?

I chose 'trust this computer', but other info notice on Mac it generally say "trust the computer to access the camera on the device', I chose not allow

**Comment by CC-q** [comment]
@yuzhidi 
Hello～ I met the same question with u, have u solved it ? If yes, could u tell me the answer?

**Comment by William-HL1991** [comment]
I met the same problem too.
The build tools is Xcode10, when i build the project ,it return 
```mkdir: build: File exists
CMake Warning at /usr/local/Cellar/cmake/3.12.4/share/cmake/Modules/Platform/Darwin-Initialize.cmake:125 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk

  because the directory does not exist.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.4/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:2 (project)


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/Downloads/ios-minicap/build
[ 14%] Building CXX object CMakeFiles/ios_minicap.dir/src/minicap.cpp.o
In file included from /Users/user/Downloads/ios-minicap/src/minicap.cpp:1:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not
      found
#include_next <stdio.h>
              ^~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/ios_minicap.dir/src/minicap.cpp.o] Error 1
make[1]: *** [CMakeFiles/ios_minicap.dir/all] Error 2
make: *** [all] Error 2
 ```
After that,When i run the script, have the same problem.

**Comment by kungger888** [comment]
@yuzhidi
I met the same question, My version of the system is macOS Mojave 10.14.2 and My mobile is iPhone XS MAX.have you solved it?

**Comment by zhaoxuncn** [comment]
I met the same question, and sloved it.  on mac find "system Preferenecs" -> "Security & Privacy" -> "Camera" -> check "Terminal"
![image](https://user-images.githubusercontent.com/13272336/55772534-2eaf3b00-5abf-11e9-8215-73808aa69d8f.png)

**Comment by sorccu** [comment]
Awesome finding. Thanks for sharing!

**Comment by yuzhidi** [comment]
thx @kungger888
