### ISSUE TITLE
Is it possible to compile a executable file run on jailbreak iphone( like minicap for android )

### ISSUE THREAD

**Issue by listeng** [nwlunatic/ios-minicap#7]
Is it possible to compile a executable file run on jailbreak iphone( like minicap for android ), and receiving screen data through wifi or iproxy( like adb forward )? Thanks.

**Comment by nwlunatic** [comment]
The executable file is working from macOS side. You don't have to run it on iphone. I don't know the specific of jailbreaked iphones, but i think it shouldn't matter.

**Comment by nwlunatic** [comment]
Or, if you just curious, i think it is possible. But forcing user to jailbreak iphone is a wrong thing to ask.
