### ISSUE TITLE
Be sure to run `ios-minicap --port 12345`

### ISSUE THREAD

**Issue by chsasaw** [nwlunatic/ios-minicap#9]
Run 'node app.js' and then open 'http://localhost:9002/', sometimes got this:
```
Listening on port 9002
Got a client
{ Error: connect ETIMEDOUT 127.0.0.1:12345
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 12345 }
Be sure to run `ios-minicap --port 12345`
```
anything wrong?

**Comment by nwlunatic** [comment]
If you've started `ios-minicap` on port `12345` before running `node app.js`, then it is haven't got first frame from device to setup. Currently it is waiting for a frame and only then starting socket server.

**Comment by chsasaw** [comment]
So what can I do now? How to stop `ios-minicap`, and restart using `node app.js`?

**Comment by nwlunatic** [comment]
follow the readme instructions:

1. first, it one terminal window/tab, run `./run.sh`, it will start `ios-minicap`
2. wait for it to show you `banner`
3. then, in another terminal windows/tab, run `node example/app.js`
